### ISSUE TITLE
style Sign up page

### ISSUE THREAD

**Issue by interstellaridea** [thomascarli/roastdata#21]

**Comment by thomascarli** [comment]
@interstellaridea isn't this done?

**Comment by interstellaridea** [comment]
Yup!

On Feb 5, 2017 12:45 PM, "Tommy Carli" <notifications@github.com> wrote:

@interstellaridea <https://github.com/interstellaridea> isn't this done?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/thomascarli/roastdata/issues/21#issuecomment-277547818>,
or mute the thread

**Comment by interstellaridea** [comment]
fix a typo in this 
head was rostdata not R O A S T  data -_-
pushed into master.
